### ISSUE TITLE
feat: add example for invoking a lambda function in integ tests

### ISSUE THREAD

**Issue by mavogel** [aws-samples/cdk-integ-tests-sample#7]
Thank you for the great repo and example code coming with the [blog post](https://aws.amazon.com/de/blogs/devops/how-to-write-and-execute-integration-tests-for-aws-cdk-applications/) :) 

Is it possible to add an example for a `NodejsFunction` in the `functions/my-func-handler.ts` with the content

```ts
import * as AWS from 'aws-sdk';
const SES = new AWS.SES({ region: 'eu-west-1' });
export const handler = async (event: any) => {
  // Note: this is NOT wrapped into another object... 🤔
  const k1 = event.k1 || 'k1-default';
  try {
    await SES.sendEmail({/*...*/}}).promise();
    return { resultCode: 200 };
  } catch (err) {
    return { resultCode: 500, err: err };
  }
};
```

and the `integ.test.ts` file containing
```ts
const myfunc = new NodejsFunction(stackUnderTest, 'my-func-handler', {
  entry: path.join(__dirname, 'functions', 'my-func-handler.ts'),
  runtime: lambda.Runtime.NODEJS_18_X,
  timeout: Duration.minutes(5),
  // works ... ✅
  initialPolicy: [
    new iam.PolicyStatement({
      actions: [
        'ses:SendEmail',
      ],
      resources: ['*'],
    }),
  ],
});

// ...
const myAssertion = integ.assertions
.invokeFunction({
  functionName: myfunc.functionName,
  logType: LogType.TAIL,
  invocationType: InvocationType.REQUEST_RESPONE, // to run it synchronously
  payload: JSON.stringify({
    k1: 'v1',
    k2: 'v2',
  }),
}).expect(ExpectedResult.objectLike({
  // Note: it's wrapped into a Payload object 🤔 Keep in mind while asserting
  Payload: {
    {resultCode:  200},
  }
}),
),

// 🛑 whereas this does not work -> gives a 403 
// myAssertion.provider.addToRolePolicy({
//   Effect: 'Allow',
//   Action: [
//     'ses:SendEmail',
//   ],
//   Resource: [
//     '*',
//   ],
// });
```

This would be helpful. I found most code in the linked reference.

## References
- https://docs.aws.amazon.com/cdk/api/v2/docs/integ-tests-alpha-readme.html#examples
- https://github.com/aws/aws-cdk/blob/v1-main/INTEGRATION_TESTS.md#assertions
- https://github.com/aws/aws-cdk/blob/3528e3de5b5dd0a520624d4af73413370dcdc434/packages/@aws-cdk/aws-apigateway/test/integ.domain-name.ts#L232

**Comment by phch** [comment]
Typically that ```NodejsFunction``` would go into your stack under test with the appropriate permissions for ```ses:SendEmail```. Then in your integration test file you would write assertions in that folder.

This code repo is aligned to our blog example, so we will be keeping this example with the sample application flow.

**Comment by mavogel** [comment]
Hi @phch, would it be an option to extend / update the repo AND the corresponding blog post?
